import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
    <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
    >
    <div>
        <nav className="fixed top-0 left-0 w-full bg-white shadow-md z-50">
            <div className="container mx-auto px-6 py-4 flex justify-between items-center">
                {/* Logo */}
                <div className="text-xl font-bold text-blue-500">
                    MyLogo
                </div>

                {/* Center Menu */}
                <div className="flex space-x-6">
                     <Link className="text-gray-700 hover:text-blue-500" href="/dashboard">Главная</Link>
                    {/*<a href="#" className="text-gray-700 hover:text-blue-500">Главная</a>*/}
                    <a href="#" className="text-gray-700 hover:text-blue-500">Топ-каперы</a>
                    <a href="#" className="text-gray-700 hover:text-blue-500">События</a>
                </div>
                    <Link className="bg-blue-500 text-white px-4 py-2 rounded-md hover:bg-blue-600" href="/registration">Регистрация</Link>
            </div>
        </nav>
    </div>
    {children}
    <footer className="mt-6 text-center text-gray-600">
        <p>© 2025 Dashboard. All rights reserved.</p>
    </footer>
    </body>
    </html>
  );
}
